project:
  type: website
  output-dir: _site

website:
  title: "Micah Gifford"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer:
    left: "Â© 2026 Micah Gifford"
    right:
      - text: "LinkedIn"
        href: https://www.linkedin.com/in/micah-gifford-4a741026a/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    
editor: visual

